### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by lieblichaaron** [lieblichaaron/queue-app#16]
Julian, make sure to fix the text so that it doesn't show up over the modal. I also noticed that the carousel changes size a bit as you switch the picture. try and fix that as well.
<img width="303" alt="Screen Shot 2021-01-18 at 14 21 23" src="https://user-images.githubusercontent.com/48128556/104914969-984cc080-5998-11eb-9c54-282c6494bbec.png">

**Comment by LangeJM** [comment]
ece8883: Fixed > Added consistent sizing for all images
e6ac647: Fixed > I had to actually make chances to the carousel component and add there a div element that holds the caption and displays it on the images. The styling is a bit different but I actually might like it better. Can be easily adjusted though.

**Comment by lieblichaaron** [comment]
looks good, one other thing, just link the get started buttons to the signup modal.

**Comment by LangeJM** [comment]
Fixed!
