### ISSUE TITLE
Account Settings: Design improvement suggestions  

### ISSUE THREAD

**Issue by LangeJM** [lieblichaaron/queue-app#78]
- No padding-left for text in input fields (at least when in edit mode, doesn't look good)
- I really like the effect of the input fields become editable with different background color, but because you're actually use different elements, they jump between states (edit/ non-edit)

**Comment by JakeRSA** [comment]
I agree about the padding thing. Will look at the sign up/ sign in modals to see how you did it.
re the jumping between states, I'm not really sure what you're referring to. Do you mean that the elements change their y-position when toggling? I can change that. (btw I'm not using different elements but I am changing the css class when they're toggled between edit/no-edit)

**Comment by LangeJM** [comment]
Yes, the y-position. What I meant was that they are different types and that's why the dimension are different as well.
It's not crucial. I just wanted us to have it somewhere.
